import { Navbar, Footer } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-[#7285d362]`}>
				<header className="bg-[#ffffff99] max-w-screen-md mx-auto">
					<Navbar />
				</header>
				<main className="bg-[#ffffff99] max-w-screen-md mx-auto">{children}</main>
				<footer className="bg-[#ffffff99] max-w-screen-md mx-auto">
					<Footer />
				</footer>
			</body>
		</html>
	);
}
